### ISSUE TITLE
Update to the Python Linked List Implementation

### ISSUE THREAD

**Issue by Ndohjapan** [Ndohjapan/data-structure#5]
Can you add a way of keeping track of the size of the linked list.

At the init function of the LinkedList class you can add something like this.
`self.size = 0`

Then each time you add an element at the beginning, you then increase the size

`self.size += 1`

Also create a main function to run the file and add sample elements into the linkedlist and also print it.

    if __name__ == '__main__':
        LL = LinkedList()

        LL.add_at_beginning(12)
        LL.add_at_beginning(4)
        LL.add_at_beginning(3)

        LL.print_LinkedList()

Then the print out should look like this
`3 -> 4 -> 12 -> END`

**Comment by Shopiley** [comment]
Hi, I could work on this.

**Comment by Ndohjapan** [comment]
https://github.com/Ndohjapan/data-structure/pull/7
